var latky = {
  "anabolické steroidy, SARM": { "Oficiální skupina":"ANABOLICKÉ LÁTKY", "Skupina sportů":"silové sporty, sprinty, vytrvalostní sporty", "Sport":"?", "Účel":"Zvýšení svalové síly a urychlení regenerace", "Pozitivní efekty":"mění struru svalu tak, že dochází k jich růstu, zvýšení síly kontrakce a přestavba struktury svalu, snížení množství tuku", "Negativní efekty":"mužské rysy u žen, riziko náhlého úmrtí, riziko zvětšení a karcinomu prostaty, gynekomastie u mužů, psychické změny - agresivita, snížení sexuální aktivity"},
  "clenbuterol": { "Oficiální skupina":"ANABOLICKÉ LÁTKY", "Skupina sportů":"silové sporty, sprinty, vytrvalostní sporty", "Sport":"kulturistika", "Účel":"Zlepšení síly a strukrury svalo ( vyrýsování)", "Pozitivní efekty":"změna struktury svalu, zvýšení anaerobní kapacity, snížení % tuku", "Negativní efekty":"arytmie, třes, psychické změny"},
  "EPO a podobné látky ": { "Oficiální skupina":"PEPTIDOVÉ HORMONY", "Skupina sportů":"vytrvalostní sporty", "Sport":"?", "Účel":"Zvýšení aerobní kapacity", "Pozitivní efekty":"zvýšení počtu červených krvinek", "Negativní efekty":"náhlá srdeční smrt, mozkové příhody "},
  "Růstový hormon a podobné látky": { "Oficiální skupina":"RŮSTOVÉ FAKTORY", "Skupina sportů":"silové sporty, sprinty, vytrvalostní sporty", "Sport":"?", "Účel":"Urychlení regenerace, zvýšení svalové síly", "Pozitivní efekty":"změna metabolismu, ne zcela jasné působení", "Negativní efekty":"porucha vnitřního prostředí, akromegalie, "},
  "Salbutamol a další": { "Oficiální skupina":"BETA2- AGONISTÉ", "Skupina sportů":"sprinty, vytrvalostní sporty", "Sport":"?", "Účel":"Zlepšení maximálního výkonu a zlepšení práce s dechem", "Pozitivní efekty":"Snížení odporu dýchacích cest a zvýšení metabolismu glukózy ve svalech", "Negativní efekty":"Třes, snížení výkonu, arytmie, teploty"},
  "Inzulin a další": { "Oficiální skupina":"HORMONOVÉ A METABOLICKÉ MODULÁTORY", "Skupina sportů":"silové sporty, sprinty, vytrvalostní sporty", "Sport":"?", "Účel":"Zlepšení maximálního výkonu", "Pozitivní efekty":"Urychlení metabolismu glukózy ve svalech", "Negativní efekty":"Rozvrat vnitřního prostředí, jaterní a ledvinné selhání"},
  "krevní transfuze": { "Oficiální skupina":"MANIPULACE S KRVÍ A KREVNÍMI KOMPONENTAMI", "Skupina sportů":"vytrvalostní sporty", "Sport":"?", "Účel":"Zvýšení aerobní kapacity", "Pozitivní efekty":"zvýšení počtu červených krvinek", "Negativní efekty":"náhlá srdeční smrt, mozkové příhody "},
  "modifikace genetické informace": { "Oficiální skupina":"GENOVÝ DOPING", "Skupina sportů":"silové sporty, sprinty, vytrvalostní sporty", "Sport":"?", "Účel":"Zlepšení regenerace, zvýšení aerobní kapacity, zvýšení anaerobní kapacity", "Pozitivní efekty":"Dle použitíé metody", "Negativní efekty":"Mnoho možných potencionálně smrtených či závažných efektů"},
  "amfetamin, kokain, marihuana a další": { "Oficiální skupina":"STIMULANCIA, NARKOTIKA A KANABINOIDY", "Skupina sportů":"silové sporty, sprinty, vytrvalostní sporty", "Sport":"F1", "Účel":"Zvýšit výkon odstraněním únavy a navozením euforie", "Pozitivní efekty":"Snižují pocit únavy působením na centrální nervový systém, zvyšují výkon", "Negativní efekty":"Třes, arytmie, náhlá srdeční smrt, selhání životních funkcí, psychické nemoci"},
  "kortizol a další": { "Oficiální skupina":"GLUKOKORTIKOIDY", "Skupina sportů":"silové sporty, sprinty, vytrvalostní sporty", "Sport":"?", "Účel":"Urychlení regenerace", "Pozitivní efekty":"změnou metabolismu svalové buňky uyrchlit regeneraci a umožnit vysoké dávky tréninku", "Negativní efekty":"Metabolický rozvrat, osteoporoza, endokrinní poruchy, poruchy imunity"},
  "metoprolol a další": { "Oficiální skupina":"BETA-BLOKÁTORY", "Skupina sportů":"střelba", "Sport":"střelba", "Účel":"Uklidnení před a během výkonu", "Pozitivní efekty":"Snížení tepové frekvence, snížení metabolismu", "Negativní efekty":"Náhrá srdeční smrt, arytmie"},
  "motor v kole": { "Oficiální skupina":"MECHANICKÁ PODPORA", "Skupina sportů":"cyklistika", "Sport":"cyklistika", "Účel":"Zvýšit výkon", "Pozitivní efekty":"Zvýšení výkonu v maximálních zátěžích", "Negativní efekty":"nemá"}
};