var latky = {
  "Testosteron, nandrolon, SARM": { "img":"testosteron", "skupina":"Anabolické steroidy", "img_sporty":"", "sporty":"Všechny", "ucel":"Rychlejší tvorba svalové hmoty", "mechanismus":"Vyšší dávka mužských hormonů vede k rychlejší tvorbě svalstva, kostní tkáně, červených krvinek a nervových propojení", "rizika":"Riziko náhlého úmrtí, poruchy jater/ledvin, psychické změny (agresivita, zvýšení/snížení sexuální aktivity), u žen mužské rysy, u mužů riziko zvětšení a karcinomu prostaty, gynekomastie (zvětšené prsní žlázy)", "aplikace":"Prášek", "zdroje":""},
  "Erytropoetin": { "img":"erytropoetin", "skupina":"Peptidové hormony", "img_sporty":"cyklo", "sporty":"cyklistika, běžecké lyžování, triatlon, sprinty, dlouhé běhy, chůze", "ucel":"Zlepšení vytrvalosti", "mechanismus":"Zvýšení počtu červených krvinek", "rizika":"Náhlá srdeční smrt, mozkové příhody ", "aplikace":"Injekce", "zdroje":""},
  "Lidský růstový hormon": { "img":"rust_hormon", "skupina":"Růstové faktory", "img_sporty":"cyklo", "sporty":"cyklistika, sprinty, baseball", "ucel":"Rychlejší tvorba svalové hmoty, rychlejší léčba poranění", "mechanismus":"Urychlení regenerace změnou metabolismu, není zcela jasné působení", "rizika":"Porucha vnitřního prostředí, akromegalie (nadměrný růst částí těla nebo vnitřních orgánů)", "aplikace":"Injekce", "zdroje":""},
  "Clenbuterol": { "img":"clenbuterol", "skupina":"Beta2- agonisté", "img_sporty":"kultur, sprint, beh, koule, vzper, plavani", "sporty":"culturistika, sprinty, dlouhé běhy, koule, kladivo, vzpírání, plavání, ragby", "ucel":"Zachování svalové hmoty, lepší vyrýsování svalů", "mechanismus":"Uvolňuje svaly v oblasti dýchacích cest, jako vedlejší efekt zrychluje metabolismus a tím i spalování tuku. Nedochází přitom ke ztrátě svalové hmoty, podle některých studií dokonce urychluje růst svalů.", "rizika":"Arytmie, třes, psychické změny", "aplikace":"Prášek", "zdroje":"https://legionathletics.com/clenbuterol/"},
  "Salbutamol": { "img":"salbutamol", "skupina":"Beta2- agonisté", "img_sporty":"cyklo, bezky, beh", "sporty":"cyklistika, běžecké lyžování, dlouhé běhy, trojskok", "ucel":"Zlepšení práce s dechem, možné zlepšení maximálního výkonu", "mechanismus":"Uvolňuje svaly v oblasti dýchacích cest, proto se používá jako lék na astma. Podle některých studií vede ke zvýšení maximální výkonu.", "rizika":"Třes, snížení výkonu, arytmie, teploty", "aplikace":"Inhalátor na astma", "zdroje":"https://www.ncbi.nlm.nih.gov/pubmed/8781870"},
  "Inzulin": { "img":"inzulin", "skupina":"Hormonové/metabolické modulátory", "img_sporty":"cyklo, kultur, sprint", "sporty":"cyklistika, kulturistika, sprinty", "ucel":"Rychlejší tvorba svalové hmoty, lepší vyrýsování svalů", "mechanismus":"Hladina inzulinu ovlivňuje spalování sacharidů. Nízká hladina při nečinnosti znamená nízké ukládání tuků, vysoká hladina při tréninku vede k rychlejšímu růstu svalů.", "rizika":"Rozvrat vnitřního prostředí, jaterní a ledvinné selhání", "aplikace":"Injekce", "zdroje":""},
  "Krevní transfúze": { "img":"transfuze", "skupina":"", "img_sporty":"cyklo, bezky, beh", "sporty":"cyklistika, běžecké lyžování, biatlon", "ucel":"Zlepšení vytrvalosti", "mechanismus":"Transfúzí cizí krve – případně vlastní zmražené krve – po výkonu se doplní počet červených krvinek", "rizika":"Náhlá srdeční smrt, mozková příhoda ", "aplikace":"Krevní vak", "zdroje":""},
  "Genový doping": { "img":"genovy_doping", "skupina":"", "img_sporty":"dolly", "sporty":"Ovečka Dolly", "ucel":"Různé efekty", "mechanismus":"Různé modifikace genetické informace", "rizika":"Mnoho možných potencionálně škodlivých či smrtelných efektů", "aplikace":"Blob", "zdroje":""},
  "Amfetamin, kokain, marihuana": { "img":"trava", "skupina":"Narkotika", "img_sporty":"f1, fotbal", "sporty":"F1, fotbal, tenis", "ucel":"Relaxace, navození euforie", "mechanismus":"Různé působení na centrální nervový systém", "rizika":"Třes, arytmie, náhlá srdeční smrt, selhání životních funkcí, psychické nemoci", "aplikace":"Cigareta", "zdroje":""},
  "Kortizol": { "img":"kortizol", "skupina":"Glukokortikoidy", "img_sporty":"cyklo, kultur", "sporty":"cyklistika, kulturistika", "ucel":"Rychlejší tvorba svalové hmoty", "mechanismus":"Hormon kortizol, který se produkuje při stresu nebo delší fyzické zátěži, brání tvorbě svalů. Snížení jeho hladiny vede k růstu svaloviny i při delším tréninku.", "rizika":"Metabolický rozvrat, osteoporóza, poruchy endokrinních žláz, poruchy imunity", "aplikace":"Kapky do nosu", "zdroje":"http://drdoping.com/blog/cortisol-and-sport/"},
  "Metoprolol": { "img":"metoprolol", "skupina":"Beta-blokátory", "img_sporty":"luk", "sporty":"lukostřelba, golf, F1, skoky na lyžích", "ucel":"Uklidnění před a při výkonu", "mechanismus":"Snížení tepové frekvence a krevního tlaku", "rizika":"Náhlá srdeční smrt, arytmie", "aplikace":"Prášek", "zdroje":""},
  "Pomocný motor": { "img":"pomocny_motor", "skupina":"Mechanický doping", "img_sporty":"cyklo", "sporty":"cyklistika", "ucel":"Zvýšení výkonu v maximálních zátěžích", "mechanismus":"Motor v rámu kola", "rizika":"Kouř", "aplikace":"Bazmek (http://supercycling.cz/assets/Uploads/DopingElektro-motor-cl.jpg)", "zdroje":""}
};